const cake = [
  {
    name: "Vanila Cake",
    img: "https://imgs.search.brave.com/t2knWo7vQpt0vaDsbNxvBmZFN1x5BC4xOFqMHpXjUVA/rs:fit:474:429:1/g:ce/aHR0cHM6Ly9hbGl0/dGxlY2FrZS5jb20v/d3AtY29udGVudC91/cGxvYWRzLzIwMTkv/MDQvVmFuaWxsYS1D/cmVhbS1DYWtlLWUx/NTU0ODUwNTkwNjM5/LmpwZw",
    size: ["oneTier", "twoTier", "threeTier"],
    price: [{ oneTier: 400, twoTier: 600, threeTier: 800 }],
    index: 1,
  },
  {
    name: "Pineapple Cake",
    img: "https://assets.winni.in/product/primary/2022/8/72487.jpeg?dpr=2&w=220",
    size: ["oneTier", "twoTier", "threeTier"],
    price: [{ oneTier: 450, twoTier: 700, threeTier: 900 }],
    index: 2,
  },
  {
    name: "Strawberry Cake",
    img: "https://aclassictwist.com/wp-content/uploads/2020/08/Fresh-Strawberry-Cake-with-Strawberry-Frosting-3-480x360.jpg",
    size: ["oneTier", "twoTier", "threeTier"],
    price: [{ oneTier: 450, twoTier: 700, threeTier: 900 }],
    index: 3,
  },
  {
    name: "Red Velvet Cake",
    img: "https://www.doughandcream.com/wp-content/uploads/2022/12/Red-Velvet-Cake.jpg",
    size: ["oneTier", "twoTier", "threeTier"],
    price: [{ oneTier: 450, twoTier: 700, threeTier: 900 }],
    index: 4,
  },
  {
    name: "Chocolate Cake",
    img: "https://www.labonelfinebaking.shop/wp-content/uploads/2021/02/CLASSIC-CHOCOLATE-CAKE.jpg",
    size: ["oneTier", "twoTier", "threeTier"],
    price: [{ oneTier: 500, twoTier: 750, threeTier: 1000 }],
    index: 5,
  },
  {
    name: "Chocolate Truffle Cake",
    img: "https://media.bakingo.com/sq-choco-truffle-cake0005choc-AA.jpg",
    size: ["oneTier", "twoTier", "threeTier"],
    price: [{ oneTier: 550, twoTier: 800, threeTier: 1100 }],
    index: 6,
  },
  {
    name: "Simple Sponge Cake",
    img: "https://drivemehungry.com/wp-content/uploads/2022/04/sponge-cake-16.jpg",
    size: ["oneTier", "twoTier", "threeTier"],
    price: [{ oneTier: 250, twoTier: 350, threeTier: 500 }],
    index: 7,
  },
  {
    name: "Black Forest Cake",
    img: "https://www.doughandcream.com/wp-content/uploads/2022/12/Black-Forest-Cake.jpg",
    size: ["oneTier", "twoTier", "threeTier"],
    price: [{ oneTier: 500, twoTier: 750, threeTier: 1000 }],
    index: 8,
  },
  {
    name: "Oreo Cake",
    img: "https://www.lifeloveandsugar.com/wp-content/uploads/2015/02/Chocolate-Oreo-Cake2.jpg",
    size: ["oneTier", "twoTier", "threeTier"],
    price: [{ oneTier: 500, twoTier: 750, threeTier: 1000 }],
    index: 9,
  },
  {
    name: "Cup Cake",
    img: "https://www.bhg.com/thmb/iL-5Q6gGjmXkxCKqEovughTLQAo=/3000x0/filters:no_upscale():strip_icc()/how-to-bake-how-to-make-cupcakes-hero-01-12c03f3eff374d569b0565bff7d9e597.jpg",
    size: ["oneTier", "twoTier", "threeTier"],
    price: [{ oneTier: 33, twoTier: "NaN", threeTier: "NaN" }],
    index: 10,
  },
  {
    name: "White Forest Cake",
    img: "https://www.cakehut.in/image/cache/catalog/2021%20cake%20photos/White%20Forestt-1821x1581.jpg.webp",
    size: ["oneTier", "twoTier", "threeTier"],
    price: [{ oneTier: 500, twoTier: 750, threeTier: 1000 }],
    index: 11,
  },
  {
    name: "Kesar Pista Cake",
    img: "https://cdn.shopify.com/s/files/1/1758/8043/products/Kesarpista2_x700.jpg?v=1605415798",
    size: ["oneTier", "twoTier", "threeTier"],
    price: [{ oneTier: 600, twoTier: 900, threeTier: 1200 }],
    index: 12,
  },
];
export default cake;
